### PR TITLE
Include Thread name in logged messages

### PR DESCRIPTION
**Pull request by loehnertj**
``hanging_threads`` has been very useful for me. This change makes it even more useful for programs managing many threads (e.g. GUI + multiple network connections), esp. when multiple threads are blocked at the same point.

Open for review.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi @loehnertj, thanks for that contribution.

The build shows that some Python versions have an error:
https://travis-ci.org/niccokunzmann/hanging_threads/builds/580697779?utm_source=github_status&utm_medium=notification
Please have a look.

I do not think it is necessary to break compatibility for this. What do you think?

**Comment by loehnertj** [comment]
Hi Nicco, I agree absolutely. *However*, looking at the error logs, it seems to me that the failing builds are a problem with Travis itself (older Python versions not available anymore).

    Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-2.6.tar.bz2

    0.15s$ curl -sSf -o python-2.6.tar.bz2 ${archive_url}

    curl: (22) The requested URL returned error: 404 Not Found

    Unable to download 2.6 archive. The archive may not exist. Please consider a different version.

(also, the package is apparently only installed without actually testing anything...)

According to the python docs, the possibly-critical APIs (``Thread.ident`` / ``.name``, ``dict.items``, ``str.format``) all date back to 2.6 or earlier. So I think that backwards-compat is not actually broken.

**Comment by niccokunzmann** [comment]
Wow, that seems to be true. Can you remove these lines from the .travis.yml file, so this pull request creates a green build? I will merge, then.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
