### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by artemrizhov**

### CODE REVIEW

**Comment by artemrizhov** [comment]
You cherry-picked again? :)

**Comment by niccokunzmann** [comment]
I used the squash commit ability. This is nice, if we want every commit to be a tag in the branch and it does not hurt.

**Comment by artemrizhov** [comment]
Squash does rebase. This is nice if you want to merge changes from third-party repo, but not for merging branches in your own repo. This breaks the history.

**Comment by niccokunzmann** [comment]
-.- oh no so, I will only merge, then. Thanks for telling me. Now I learned something again.

**Comment by artemrizhov** [comment]
You can reset and merge locally without PR and then do forced push to avoid extra versions :)

**Comment by niccokunzmann** [comment]
Done :) Now, I will go to bed celebrating, that I have tried out everything that could go wrong and it worked in the end.

**Pull request merged**
