### PR TITLE
Correction

### PR DESCRIPTION
**Pull request by MarkoMackic**
#52 correction

### CODE REVIEW

**Comment by artemrizhov** [comment]
I thought most changes have been merged already in #52. Why are they here again?
There is also strange problem with merged branches which I've described in #49.

**Comment by artemrizhov** [comment]
@MarkoMackic The problem is that #52 has been merged exactly the same way as #49. It has been cherry picked. So this PR conflicts with your own changes.

@niccokunzmann Do you know what's going on?

**Comment by niccokunzmann** [comment]
Yes, I tried rebase commits. I see, this leads to problems. I think, merge and squash commits are fine for PR but we should avoid the rebase commits. Sorry for the inconvenience.

**Comment by niccokunzmann** [comment]
I resolved some conflicts. Could you check all is as expected?

**Comment by MarkoMackic** [comment]
Now it's all ok. You can merge, and than I'll pull again to be in sync.

**Comment by artemrizhov** [comment]
@niccokunzmann Rebase creates totally new history, so this leads to conflict. This may be a good idea if you accept PR from somebody who is not heavily involved. Otherwise we have to wait until PR is accepted and then pull the cahnges before continuing the work.

@MarkoMackic Btw, I've noticed you pull the changes from the master branch with "no forward" option. This leads into inconvenient graph of branches. Your master branch is always going beside the main master branch and it makes hard to understand where a feature has been finished.

**Comment by artemrizhov** [comment]
@MarkoMackic So, the question is - could you please pull the change without "no forward" options? You can do this from command line or with you favorite git client by pulling directly from niccokunzmann/hanging_threads.

**Comment by MarkoMackic** [comment]
@artemrizhov is there any way to do it without "no forward" from github site, cause whenever I make changes, I pull from this master branch, make changes on my local branch, push changes, and then create PR from githtub directly. Ok, so I would pull changes directly from your repo ? Let me see how that'd work, I'll create directory tests as we'll need it soon

**Comment by artemrizhov** [comment]
@MarkoMackic I think this is impossible with pull requests, but you actually do not need any requests to pull the changes. How do you pull the changes from your github repo? You can pull the changes from niccokunzmann's repo the same way. For example, you can add a remote from the console:

    git remote add niccokunzmann git@github.com:niccokunzmann/hanging_threads.git

and then just pull from there

    git pull niccokunzmann master

**Comment by artemrizhov** [comment]
@MarkoMackic To start wroking the right way you probably will have to reset your current master branch.

    git remote add niccokunzmann git@github.com:niccokunzmann/hanging_threads.git
    git fetch niccokunzmann
    git checkout master
    git reset --hard niccokunzmann/master

And then you can push and create PRs to the master repo as usually, but when you want to get the changes back, you should do this:

    git pull niccokunzmann master

Do you use the command line git interface? If not then all these commands should be available via your favorite GUI. You can add a remote via GUI, fetch commits from it, reset your master branch to the specific commit, etc.

**Comment by MarkoMackic** [comment]
I use command line git, please look #54

**Comment by artemrizhov** [comment]
@MarkoMackic Sorry, there was a mistake in the second command: `git fetch niccokunzmann` should be used instead of `git pull niccokunzmann`.
Please let me know if you need any help.

**Pull request merged**
