### PR TITLE
Added tests folder and initial script

### PR DESCRIPTION
**Pull request by MarkoMackic**
Is this commit ok ? I pulled directly from https://github.com/niccokunzmann/hanging_threads/

### CODE REVIEW

**Comment by artemrizhov** [comment]
Yes, it looks like your branch has been started directly from niccokunzmann/master.

**Comment by MarkoMackic** [comment]
Nice, so I'll now pull directly from origin repo, push to myorigin, and initiate pull requests as usual ?

**Comment by artemrizhov** [comment]
@MarkoMackic Remember that if you commit into your master branch before you pull all the changes from niccokunzmann/master then you will not be able to pull with fast forward method. So if anybody commits to master while you are working on your master then things are broken again. To avoid such problems you should always start new branch for any feature. This way you will be able to fast forward your master branch at any time.

**Comment by MarkoMackic** [comment]
Cool, I'll create patch branch for any edits in session.

**Comment by artemrizhov** [comment]
Actually it's better to create branches for features, not for sessions. Local branches and commits is the power of git. You can always leave a branch as is and switch to another branch to work on another feature, then swtich back and so on.

**Comment by MarkoMackic** [comment]
Thanks, I'll ask you for further help if I need it :)

**Comment by artemrizhov** [comment]
@MarkoMackic Please take a look at this graph.
https://github.com/niccokunzmann/hanging_threads/network
You can see that @niccokunzmann works on branch `test-python-version` which is not merged yet. He can switch to another task at any time just by doing commit and checkout. You also can see that I left `ignore_first_threads` not merged (because now I think that was not a good idea).

> Thanks, I'll ask you for further help if I need it :)

Sure, no problem. Feel free to ask. I can give any answer to any question ;)

**Pull request merged**
